const TYPE = {
  PUBLIC_KEY: 'PUBLIC KEY',
  PRIVATE_KEY: 'PRIVATE KEY',
  RSA_PUBLIC_KEY: 'RSA PUBLIC KEY',
  RSA_PRIVATE_KEY: 'RSA PRIVATE KEY',
  CERTIFICATE: 'CERTIFICATE',
  CERTIFICATE_REQUEST: 'CERTIFICATE REQUEST',
  X509_CRL: 'X509 CRL',
  PKCS7: 'PKCS7',
  CMS: 'CMS',
  ENCRYPTED_PRIVATE_KEY: 'ENCRYPTED PRIVATE KEY',
  ATTRIBUTE_CERTIFICATE: 'ATTRIBUTE CERTIFICATE',
  CERTIFICATE_CHAIN: 'CERTIFICATE CHAIN',
};

module.exports = { TYPE };
